# Generated by Django 6.0.7 on 2026-07-12 16:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('service_required', models.CharField(choices=[('custom_software', 'Custom Software Development'), ('web_app', 'Web Application Development'), ('mobile_app', 'Mobile App Development'), ('ui_ux', 'UI/UX Design'), ('cloud', 'Cloud Solutions'), ('api_dev', 'API Development'), ('erp_crm', 'ERP / CRM Solutions'), ('maintenance', 'Maintenance & Support'), ('consulting', 'IT Consulting'), ('ai_integration', 'AI Integration'), ('other', 'Other / Not sure yet')], default='other', max_length=30)),
                ('budget', models.CharField(blank=True, choices=[('under_5k', 'Under $5,000'), ('5k_15k', '$5,000 – $15,000'), ('15k_50k', '$15,000 – $50,000'), ('over_50k', '$50,000+'), ('not_sure', 'Not sure yet')], max_length=20)),
                ('project_description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_discussion', 'In discussion'), ('won', 'Won'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Client Enquiry',
                'verbose_name_plural': 'Client Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
