# Generated by Django 5.2.16 on 2026-07-31 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('icon', models.CharField(default='school-outline', help_text="Material Design Icons name (without the 'mdi-' prefix). Ignored if an image is uploaded.", max_length=60)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('short_description', models.CharField(blank=True, help_text='Optional one-line summary shown on the course card.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this course from the website.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('icon', models.CharField(default='code-braces', help_text="Material Design Icons name (without the 'mdi-' prefix), e.g. 'code-braces'. Browse icons at pictogrammers.com/library/mdi/. Ignored if an image is uploaded below.", max_length=60)),
                ('image', models.ImageField(blank=True, help_text='Optional icon/image. If left blank, the icon name above is used.', null=True, upload_to='services/')),
                ('short_description', models.CharField(help_text='One or two sentences shown on the service card.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional longer description for a future service detail page.')),
                ('features', models.TextField(blank=True, help_text='Optional. One feature per line — shown as a bullet list.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to hide this service from the website.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='clientenquiry',
            name='service_required',
            field=models.CharField(choices=[('custom_software', 'Custom Software Development'), ('web_app', 'Web Application Development'), ('ui_ux', 'UI/UX Design'), ('erp_crm', 'ERP / CRM Solutions'), ('maintenance', 'Maintenance & Support'), ('consulting', 'IT Consulting'), ('ai_integration', 'AI Integration'), ('seo_services', 'SEO Services'), ('student_projects', 'College Student Projects'), ('other', 'Other / Not sure yet')], default='other', max_length=30),
        ),
    ]
