# Generated by Django 4.2.30 on 2026-07-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_video_youtube_url_alter_video_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classroom_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='classroom_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
