# Generated by Django 5.2.16 on 2026-07-31 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Teacher(s) who own/manage this course. Set by Admin.', limit_choices_to={'role': 'teacher'}, related_name='teaching_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
